/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import com.placeholder.PlaceHolder;
import db.Conection.Conexao;
import java.awt.Color;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.JobName;
import javax.print.attribute.standard.MediaSizeName;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author icety
 */
public class TelaCaixa extends javax.swing.JInternalFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Conexao con = new Conexao();

    DefaultTableModel modelo, modelo2;
    PlaceHolder placeholder;
    /**
     * Creates new form TelaCaixa
     */
    public TelaCaixa() {
        initComponents();
        quantidadeProduto.setDocument(new SoNumeros());
        valor_recebido.setDocument(new SoNumeroEPontos());
        
        placeholder = new PlaceHolder(txtPesquisaVenda, "Digite o nome do produto..");
        total.setForeground(Color.GREEN);
        btnFinalizarContaCaixa.setEnabled(false);
    
    }
    
    public void pesquisarProdutoCadastrado() {
//        String sql = "select * from produtos where nomeproduto like ?";
//        try {
//            pst = conexao.prepareStatement(sql);
//            
//            pst.setString(1, txtPesquisaVenda.getText() + "%");
//            rs = pst.executeQuery();
//            
//            tblPesquisaProdutoVenda.setModel(DbUtils.resultSetToTableModel(rs));
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
        
           try {
            ((DefaultTableModel) tblPesquisaProdutoVenda.getModel()).setNumRows(0);
            tblPesquisaProdutoVenda.updateUI();
            conexao = Conexao.conector();
            ResultSet rs = con.ConsultarProduto(txtPesquisaVenda.getText());
             String _nome = null, _preco = null, _tamanho = null, _especial = null;
             
             while (rs.next()) {
                    _nome = rs.getString("nomeproduto");
                    _preco = rs.getString("preco");
                    _tamanho = rs.getString("tamanho");
                    _especial = rs.getString("especial");

                    modelo = (DefaultTableModel) tblPesquisaProdutoVenda.getModel();
                    modelo.addRow(new Object[]{"" + _nome, _preco, _tamanho, _especial});

                }
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setar_campos() {
        
        java.util.Date data = new java.util.Date();
        DateFormat formatadorData = DateFormat.getDateInstance(DateFormat.SHORT);
        txtDataCaixa.setText(formatadorData.format(data));
       
        txtValorItem.setText(tblPesquisaProdutoVenda.getValueAt((tblPesquisaProdutoVenda.getSelectedRow()), 1).toString());
        
        JOptionPane.showMessageDialog(null, "Os dados da venda estão no formulário", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesquisaProdutoVenda = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableVenda = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        quantidadeProduto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtValorItem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        valor_recebido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        troco = new javax.swing.JTextField();
        btnFinalizarContaCaixa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtDataCaixa = new javax.swing.JTextField();
        txtPesquisaVenda = new javax.swing.JTextField();
        btnQauntidadeCaixa = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnValorRecebidoCaixa = new javax.swing.JButton();
        tipoVenda = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(680, 650));

        jPanel1.setBackground(new java.awt.Color(27, 247, 247));

        jLabel1.setFont(new java.awt.Font("Fira Code Light", 1, 28)); // NOI18N
        jLabel1.setText("Fluxo de Venda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(680, 430));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconfinder_search_172546.png"))); // NOI18N

        tblPesquisaProdutoVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Tamanho", "Especial"
            }
        ));
        tblPesquisaProdutoVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesquisaProdutoVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPesquisaProdutoVenda);

        jLabel4.setFont(new java.awt.Font("Fira Code Light", 1, 14)); // NOI18N
        jLabel4.setText("Tabela de Pesquisa ");

        tableVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Valor", "Quantidade", "Total"
            }
        ));
        tableVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVendaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableVendaMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tableVenda);

        jLabel5.setFont(new java.awt.Font("Fira Code Light", 1, 14)); // NOI18N
        jLabel5.setText("Itens da Venda");

        jLabel7.setFont(new java.awt.Font("Fira Code Light", 1, 14)); // NOI18N
        jLabel7.setText("*Quantidade:");

        quantidadeProduto.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        quantidadeProduto.setPreferredSize(new java.awt.Dimension(196, 35));
        quantidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeProdutoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Fira Code Light", 1, 14)); // NOI18N
        jLabel8.setText("Valor por item:");

        txtValorItem.setFont(new java.awt.Font("Fira Code SemiBold", 1, 14)); // NOI18N
        txtValorItem.setEnabled(false);
        txtValorItem.setPreferredSize(new java.awt.Dimension(196, 35));

        jLabel9.setFont(new java.awt.Font("Fira Code Light", 1, 14)); // NOI18N
        jLabel9.setText("Valor Total:");

        total.setBackground(new java.awt.Color(1, 83, 245));
        total.setFont(new java.awt.Font("Fira Code SemiBold", 1, 14)); // NOI18N
        total.setForeground(java.awt.Color.green);
        total.setEnabled(false);
        total.setPreferredSize(new java.awt.Dimension(196, 35));
        total.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                totalCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                totalInputMethodTextChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Fira Code Light", 1, 14)); // NOI18N
        jLabel10.setText("*Valor Recebido:");

        valor_recebido.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        valor_recebido.setPreferredSize(new java.awt.Dimension(196, 35));
        valor_recebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_recebidoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Fira Code Light", 1, 14)); // NOI18N
        jLabel11.setText("Troco:");

        troco.setFont(new java.awt.Font("Fira Code SemiBold", 1, 14)); // NOI18N
        troco.setForeground(new java.awt.Color(233, 1, 21));
        troco.setEnabled(false);
        troco.setPreferredSize(new java.awt.Dimension(196, 35));

        btnFinalizarContaCaixa.setBackground(new java.awt.Color(27, 50, 247));
        btnFinalizarContaCaixa.setText("Finalizar Pedido");
        btnFinalizarContaCaixa.setPreferredSize(new java.awt.Dimension(148, 40));
        btnFinalizarContaCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarContaCaixaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(249, 26, 2));
        jButton1.setText("Cancelar Pedido");
        jButton1.setPreferredSize(new java.awt.Dimension(148, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Fira Code Light", 1, 14)); // NOI18N
        jLabel12.setText("Data:");

        txtDataCaixa.setFont(new java.awt.Font("Fira Code SemiBold", 1, 14)); // NOI18N
        txtDataCaixa.setEnabled(false);
        txtDataCaixa.setPreferredSize(new java.awt.Dimension(196, 35));

        txtPesquisaVenda.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        txtPesquisaVenda.setPreferredSize(new java.awt.Dimension(241, 35));
        txtPesquisaVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaVendaKeyReleased(evt);
            }
        });

        btnQauntidadeCaixa.setFont(new java.awt.Font("Fira Code Light", 1, 12)); // NOI18N
        btnQauntidadeCaixa.setText("Inserir");
        btnQauntidadeCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQauntidadeCaixaActionPerformed(evt);
            }
        });

        jLabel13.setText("(*)Preenchimento obrigatório");

        btnValorRecebidoCaixa.setFont(new java.awt.Font("Fira Code Light", 1, 12)); // NOI18N
        btnValorRecebidoCaixa.setText("Inserir");
        btnValorRecebidoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValorRecebidoCaixaActionPerformed(evt);
            }
        });

        tipoVenda.setFont(new java.awt.Font("Fira Code", 0, 13)); // NOI18N
        tipoVenda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dinheiro", "Cartão" }));
        tipoVenda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoVendaItemStateChanged(evt);
            }
        });
        tipoVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tipoVendaMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipoVendaMouseClicked(evt);
            }
        });
        tipoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoVendaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Fira Code Light", 1, 14)); // NOI18N
        jLabel6.setText("*Tipo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(53, 53, 53))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(306, 306, 306)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(txtPesquisaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnFinalizarContaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtDataCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(quantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnQauntidadeCaixa))
                            .addComponent(jLabel9)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(tipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(valor_recebido, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnValorRecebidoCaixa))
                            .addComponent(troco, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesquisaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQauntidadeCaixa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnValorRecebidoCaixa)
                            .addComponent(valor_recebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(troco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFinalizarContaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
        );

        setBounds(0, 0, 716, 601);
    }// </editor-fold>//GEN-END:initComponents

    private void quantidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeProdutoActionPerformed
       
    }//GEN-LAST:event_quantidadeProdutoActionPerformed

    private void valor_recebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_recebidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor_recebidoActionPerformed

    private void btnFinalizarContaCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarContaCaixaActionPerformed

        
        String campoTotal = total.getText();
        
        java.util.Date data = new java.util.Date();
        DateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
        String calendar = formatDate.format(data);
        
        String tipo = (String) tipoVenda.getSelectedItem();
           
        boolean cadastrarVenda = con.cadastrarVenda(campoTotal, calendar, tipo);
        imprimirVenda();
        
        if(cadastrarVenda == true){
            JOptionPane.showMessageDialog(null, "Venda concluída com sucesso", "Venda Cadastrada", JOptionPane.INFORMATION_MESSAGE);     
                 
        quantidadeProduto.setText("");
        txtValorItem.setText("");
        total.setText("");
        valor_recebido.setText("");
        troco.setText("");
        tipoVenda.setSelectedItem("Dinheiro");
        
        btnFinalizarContaCaixa.setEnabled(false);
     
        
            for(int i = 0; i <= tableVenda.getRowCount() -1; i++){
                modelo.setRowCount(0);
                }
            
        }else{
            JOptionPane.showMessageDialog(null, "Venda não efetuada", "", JOptionPane.ERROR_MESSAGE);
        }
           
    }//GEN-LAST:event_btnFinalizarContaCaixaActionPerformed
    
    public void imprimirVenda() {        
         
       java.util.Date data1 = new java.util.Date();
       DateFormat formatadorData1 = DateFormat.getDateInstance(DateFormat.SHORT);
       String dataAtual1 = formatadorData1.format(data1);
        
        String conteudoImprimir = "";
            
        for(int i = 0; i < tableVenda.getRowCount(); i++){ 

            conteudoImprimir += modelo.getValueAt((i), 0).toString() + " - " 
                    + modelo.getValueAt((i), 2).toString() + "\n";
        }
        
        this.mandaImprimir("        MILK SHAKE MIX\n"
                + "-------------------------------- \n"
                + "        CUPOM NAO FISCAL\n"
                + "-------------------------------- \n"
                + "PRODUTO - QTD\n"
                + conteudoImprimir + ""
                + "-------------------------------- \n"
                + "        Data: " + dataAtual1 + "\n"
                + "-------------------------------- \n"
                + "    OBRIGADO PELA PREFERENCIA\n\r\n\r"
                + "\n\r \f"
                
        );        
     
    }
    
    public void mandaImprimir(String pTexto) {
        
        try {
            InputStream prin;
            prin = new ByteArrayInputStream(pTexto.getBytes("UTF-8"));
            DocFlavor docFlavor = DocFlavor.INPUT_STREAM.AUTOSENSE;
            SimpleDoc doumentoTexto = new SimpleDoc(prin, docFlavor, null);
            PrintService impressora = PrintServiceLookup.lookupDefaultPrintService();
            // pega a impicetyiiiiiressora padrão
            
            PrintRequestAttributeSet printerAttributes = new HashPrintRequestAttributeSet();
            printerAttributes.add(new JobName("Impressao", null));
            printerAttributes.add(OrientationRequested.PORTRAIT);
            printerAttributes.add(MediaSizeName.ISO_A4);
            
            DocPrintJob printJob = impressora.createPrintJob();
            try {
                printJob.print(doumentoTexto, (PrintRequestAttributeSet) printerAttributes);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Não foi possível realizar a impressão!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
            prin.close();
            
        } catch (Exception e) {
        }
        
    }
    
    private void txtPesquisaVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaVendaKeyReleased
        
        pesquisarProdutoCadastrado();
    }//GEN-LAST:event_txtPesquisaVendaKeyReleased

    private void tblPesquisaProdutoVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesquisaProdutoVendaMouseClicked
        
        setar_campos();
        
        quantidadeProduto.setText("");
        
        String produto = tblPesquisaProdutoVenda.getValueAt((tblPesquisaProdutoVenda.getSelectedRow()), 0).toString();
        String valor = tblPesquisaProdutoVenda.getValueAt((tblPesquisaProdutoVenda.getSelectedRow()), 1).toString();
        
        int numeroLinhasTabela = tableVenda.getRowCount();
       
        if(numeroLinhasTabela == 0){
          total.setText("0.0");
          ((DefaultTableModel) tableVenda.getModel()).setNumRows(0);
          tableVenda.updateUI();
        
          modelo2 = (DefaultTableModel) tableVenda.getModel();
          modelo2.addRow(new Object[]{"" + produto, "" + valor, "0", "0"});
          tableVenda.updateUI();
        }else{
            
            tableVenda.updateUI();
            
            String qtd;
            qtd = modelo2.getValueAt(tableVenda.getRowCount() -1, 2).toString();
            
            if(qtd.equals("0")){
                JOptionPane.showMessageDialog(null, "Por favor, coloque a quantidade do produto", "Importante!", JOptionPane.WARNING_MESSAGE);
            }else{
                 modelo2 = (DefaultTableModel) tableVenda.getModel();
                 modelo2.addRow(new Object[]{"" + produto, "" + valor, "0", "0" });
            
            }
        }       
    }//GEN-LAST:event_tblPesquisaProdutoVendaMouseClicked

    private void btnValorRecebidoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValorRecebidoCaixaActionPerformed

         if(valor_recebido.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo valor recebido é obrigatório");
        } else {
             double valor_produto = Double.parseDouble(total.getText());
             double valorRecebido = Double.parseDouble(valor_recebido.getText());

            if(valorRecebido < valor_produto){
                JOptionPane.showMessageDialog(null, "Valor insuficiente para o pagamento." , "Atenção !" , JOptionPane.ERROR_MESSAGE);
            }else{
                 BigDecimal valor_prod = new BigDecimal(valor_produto).setScale(2, RoundingMode.HALF_EVEN);
            BigDecimal valor_rec = new BigDecimal(valorRecebido).setScale(2, RoundingMode.HALF_EVEN);

            troco.setText("" + valor_prod.subtract(valor_rec));

            btnFinalizarContaCaixa.setEnabled(true);

            }
         }
       
    }//GEN-LAST:event_btnValorRecebidoCaixaActionPerformed

    private void btnQauntidadeCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQauntidadeCaixaActionPerformed
        
        if(quantidadeProduto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo quantidade é obrigatório");
        } else {
            String quantidade = quantidadeProduto.getText();
        
        int quantidadeConverter = Integer.parseInt(quantidade);
        
        int ultimaLinha = tableVenda.getRowCount() - 1;
        
               
        String produto = tableVenda.getValueAt((ultimaLinha), 0).toString();
        String valor = tableVenda.getValueAt((ultimaLinha), 1).toString();
        
         ((DefaultTableModel) tableVenda.getModel()).setNumRows(ultimaLinha);
          tableVenda.updateUI();
          
        float valorConverter = Float.parseFloat(valor);
        float valorTotal = quantidadeConverter *  valorConverter; 
        
        
        
          modelo = (DefaultTableModel) tableVenda.getModel();
          modelo.addRow(new Object[]{"" + produto , "" + valor, "" + quantidade, "" + valorTotal});
          
           double soma = 0;

            for(int i = 0; i < tableVenda.getRowCount(); i++){
            String valorPrecoTable = tableVenda.getValueAt(i, 3).toString();

            double valorPreco = Double.parseDouble(valorPrecoTable);
            
            soma += valorPreco;
        }

        total.setText("" + soma);
        
        }
        
        

    }//GEN-LAST:event_btnQauntidadeCaixaActionPerformed

    private void totalInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_totalInputMethodTextChanged
        
    }//GEN-LAST:event_totalInputMethodTextChanged

    private void totalCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_totalCaretPositionChanged


    }//GEN-LAST:event_totalCaretPositionChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    quantidadeProduto.setText("");
    txtValorItem.setText("");
    total.setText("");
    valor_recebido.setText("");
    troco.setText("");
        
    for(int i = 0; i <= tableVenda.getRowCount() -1; i++){
        
    modelo.setRowCount(0);
   
 }
    


    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVendaMouseClicked
        
        String valorTotal = tableVenda.getValueAt((tableVenda.getSelectedRow()), 3).toString();
        double valorTotalDouble = Double.parseDouble(valorTotal);
        
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja retirar este item da venda?",
                 "Atenção", JOptionPane.YES_NO_OPTION);
        
        if(confirma == JOptionPane.YES_OPTION){
            
          String campoTotal = total.getText();
          double campoTotalDouble = Double.parseDouble(campoTotal);
          
          double novoValor = campoTotalDouble - valorTotalDouble;
          
          total.setText("" + novoValor);
          quantidadeProduto.setText("");
          txtValorItem.setText("");
            
        int i = tableVenda.getSelectedRow();
        modelo.removeRow(i);
        
        
        }
        
        
        

    }//GEN-LAST:event_tableVendaMouseClicked

    private void tipoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoVendaActionPerformed
        
    }//GEN-LAST:event_tipoVendaActionPerformed

    private void tipoVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoVendaMouseClicked
            
    }//GEN-LAST:event_tipoVendaMouseClicked

    private void tipoVendaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoVendaItemStateChanged
        
        String tipo = (String) tipoVenda.getSelectedItem();
        String campoTotal = total.getText();
        
        if(tipo.equals("Cartão")) {
            valor_recebido.setText(campoTotal);
            troco.setText("0.00");
            
            btnFinalizarContaCaixa.setEnabled(true);
        }
    }//GEN-LAST:event_tipoVendaItemStateChanged

    private void tipoVendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoVendaMousePressed
        
    }//GEN-LAST:event_tipoVendaMousePressed

    private void tableVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVendaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tableVendaMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarContaCaixa;
    private javax.swing.JButton btnQauntidadeCaixa;
    private javax.swing.JButton btnValorRecebidoCaixa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField quantidadeProduto;
    private javax.swing.JTable tableVenda;
    private javax.swing.JTable tblPesquisaProdutoVenda;
    private javax.swing.JComboBox tipoVenda;
    private javax.swing.JTextField total;
    private javax.swing.JTextField troco;
    private javax.swing.JTextField txtDataCaixa;
    private javax.swing.JTextField txtPesquisaVenda;
    private javax.swing.JTextField txtValorItem;
    private javax.swing.JTextField valor_recebido;
    // End of variables declaration//GEN-END:variables
}
